const motos = [
   
    {
        id:'moto017',
        linea:'110',
        modelo:'Energy A/D R-2',
        marca:'Corven',
        descripcion:'LLEVALA HOY MISMO + CASCO DE REGALO ',
        metodopago:'',
        categoria:'moto',
        disponible:'si',
        year:'2019',
        imagen:'img/motos/Energy-110-R2.png',
        marcaimagen:'img/marcas/corven.png'
    },
    {
        id:'moto016',
        linea:'110',
        modelo:'Energy R/T R-2',
        marca:'Corven',
        descripcion:'LLEVALA HOY MISMO + CASCO DE REGALO ',
        metodopago:'',
        categoria:'moto',
        disponible:'si',
        year:'2019',
        imagen:'img/motos/Corven-Energy-RT.png',
        marcaimagen:'img/marcas/corven.png'
    },
    {
        id:'moto015',
        linea:'110',
        modelo:'Crono Classic 110',
        marca:'Keller',
        descripcion:'LLEVALA HOY MISMO + CASCO DE REGALO ',
        metodopago:'',
        categoria:'moto',
        disponible:'si',
        year:'2019',
        imagen:'img/motos/Keller-Crono-Full-110.png',
        marcaimagen:'img/marcas/keller.png'
    },
    {
        id:'moto014',
        linea:'110',
        modelo:'Crono Full 110',
        marca:'Keller',
        descripcion:'LLEVALA HOY MISMO + CASCO DE REGALO ',
        metodopago:'',
        categoria:'moto',
        disponible:'si',
        year:'2019',
        imagen:'img/motos/Keller-Crono-Full-110.png',
        marcaimagen:'img/marcas/keller.png'
    },
    {
        id:'moto013',
        linea:'110',
        modelo:'LD 110 Max',
        marca:'Mondial',
        descripcion:'LLEVALA HOY MISMO + CASCO DE REGALO ',
        metodopago:'',
        categoria:'moto',
        disponible:'si',
        year:'2019',
        imagen:'img/motos/Mondial-LD-110-MAX.png',
        marcaimagen:'img/marcas/mondial.png'
    },
    {
        id:'moto012',
        linea:'110',
        modelo:'Blitz Base 110',
        marca:'Motomel',
        descripcion:'LLEVALA HOY MISMO + CASCO DE REGALO ',
        metodopago:'',
        categoria:'moto',
        disponible:'si',
        year:'2019',
        imagen:'img/motos/Motomel-Blitz-Base-110.png',
        marcaimagen:'img/marcas/motomel.png'
    },
    {
        id:'moto011',
        linea:'110',
        modelo:'Blitz Full 110',
        marca:'Motomel',
        descripcion:'LLEVALA HOY MISMO + CASCO DE REGALO ',
        metodopago:'',
        categoria:'moto',
        disponible:'si',
        year:'2019',
        imagen:'img/motos/Motomel-Blitz-Full-110.png',
        marcaimagen:'img/marcas/motomel.png'
    },
    {
        id:'moto010',
        linea:'125',
        modelo:'Skua 125',
        marca:'Motomel',
        descripcion:'LLEVALA HOY MISMO + CASCO DE REGALO ',
        metodopago:'',
        categoria:'moto',
        disponible:'si',
        year:'2019',
        imagen:'img/motos/Motomel-Skua-125.png',
        marcaimagen:'img/marcas/motomel.png'
    },
    {
        id:'moto009',
        linea:'135',
        modelo:'Rouser 135',
        marca:'Bajaj',
        descripcion:'LLEVALA HOY MISMO + CASCO DE REGALO ',
        metodopago:'',
        categoria:'moto',
        disponible:'si',
        year:'2019',
        imagen:'img/motos/Bajaj-Rouser-135.png',
        marcaimagen:'img/marcas/bajaj.png'
    },
    {
        id:'moto008',
        linea:'150',
        modelo:'Boxer R/T 150',
        marca:'Corven',
        descripcion:'LLEVALA HOY MISMO + CASCO DE REGALO ',
        metodopago:'',
        categoria:'moto',
        disponible:'si',
        year:'2019',
        imagen:'img/motos/Corven-Boxer-RT-150.png',
        marcaimagen:'img/marcas/corven.png'
    },
    {
        id:'moto007' ,
        linea:'150',
        modelo:'Hunter R/T 150',
        marca:'Corven',
        descripcion:'LLEVALA HOY MISMO + CASCO DE REGALO ',
        metodopago:'',
        categoria:'moto',
        disponible:'si',
        year:'2019',
        imagen:'img/motos/Corven-Hunter-RT-150.png',
        marcaimagen:'img/marcas/corven.png'
    },
    {
        id:'moto006',
        linea:'150',
        modelo:'Miracle Cross',
        marca:'Keller',
        descripcion:'LLEVALA HOY MISMO + CASCO DE REGALO ',
        metodopago:'',
        categoria:'moto',
        disponible:'si',
        year:'2019',
        imagen:'img/motos/Keller-Miracle-150.png',
        marcaimagen:'img/marcas/keller.png'
    },      
    {
        id:'moto005',
        linea:'150',
        modelo:'Stratus Base 150',
        marca:'Keller',
        descripcion:'LLEVALA HOY MISMO + CASCO DE REGALO ',
        metodopago:'',
        categoria:'moto',
        disponible:'si',
        year:'2019',
        imagen:'img/motos/Keller-Stratus-Base-150.png',
        marcaimagen:'img/marcas/keller.png'
    },
    {
        id:'moto004',
        linea:'150',
        modelo:'CG 150 S2 Tubular',
        marca:'Motomel',
        descripcion:'LLEVALA HOY MISMO + CASCO DE REGALO ',
        metodopago:'',
        categoria:'moto',
        disponible:'si',
        year:'2019',
        imagen:'img/motos/Motomel-CG-S2-150.png',
        marcaimagen:'img/marcas/motomel.png'
    },
    {
        id:'moto003',
        linea:'150',
        modelo:'Skua 150 New Cross',
        marca:'Motomel',
        descripcion:'LLEVALA HOY MISMO + CASCO DE REGALO ',
        metodopago:'',
        categoria:'moto',
        disponible:'si',
        year:'2019',
        imagen:'img/motos/Motomel-SKUA-150.png',
        marcaimagen:'img/marcas/motomel.png'
    },
    {
        id:'moto002',
        linea:'150',
        modelo:'RX 150 Z7',
        marca:'Zanella',
        descripcion:'LLEVALA HOY MISMO + CASCO DE REGALO ',
        metodopago:'',
        categoria:'moto',
        disponible:'si',
        year:'2019',
        imagen:'img/motos/Zanella-RX-150-Z7.png',
        marcaimagen:'img/marcas/zanella.png'
    },
    
    {
        id:'moto001',
        linea:'200',
        modelo:'Rouser NS 200',
        marca:'Bajaj',
        descripcion:'LLEVALA HOY MISMO + CASCO DE REGALO ',
        metodopago:'',
        categoria:'moto',
        disponible:'si',
        year:'2019',
        imagen:'img/motos/ROUSER200.png',
        marcaimagen:'img/marcas/bajaj.png'
    }
   
    
];