const motos = [
    {
        id:'001',
        linea:'200',
        modelo:'Rouser NS 200',
        marca:'Bajaj',
        descripcion:'LLEVALA HOY MISMO + CASCO DE REGALO ',
        metodopago:'',
        categoria:'moto',
        disponible:'si',
        year:'2019',
        imagen:'img/',
        marcaimagen:'img/marcas/bajaj.png'
    },
    {
        id:'002',
        linea:'150',
        modelo:'RX 150 Z7',
        marca:'Zanella',
        descripcion:'LLEVALA HOY MISMO + CASCO DE REGALO ',
        metodopago:'',
        categoria:'moto',
        disponible:'si',
        year:'2019',
        imagen:'img/',
        marcaimagen:'img/marcas/zanella.png'
    },
    {
        id:'003',
        linea:'150',
        modelo:'Skua 150 New Cross',
        marca:'Motomel',
        descripcion:'LLEVALA HOY MISMO + CASCO DE REGALO ',
        metodopago:'',
        categoria:'moto',
        disponible:'si',
        year:'2019',
        imagen:'img/',
        marcaimagen:'img/marcas/motomel.png'
    },
    {
        id:'004',
        linea:'150',
        modelo:'CG 150 S2 Tubular',
        marca:'Motomel',
        descripcion:'LLEVALA HOY MISMO + CASCO DE REGALO ',
        metodopago:'',
        categoria:'moto',
        disponible:'si',
        year:'2019',
        imagen:'img/',
        marcaimagen:'img/marcas/motomel.png'
    },
    {
        id:'005',
        linea:'150',
        modelo:'Stratus Base 150',
        marca:'Keller',
        descripcion:'LLEVALA HOY MISMO + CASCO DE REGALO ',
        metodopago:'',
        categoria:'moto',
        disponible:'si',
        year:'2019',
        imagen:'img/',
        marcaimagen:'img/marcas/keller.png'
    },
    {
        id:'006',
        linea:'150',
        modelo:'Miracle Cross',
        marca:'Keller',
        descripcion:'LLEVALA HOY MISMO + CASCO DE REGALO ',
        metodopago:'',
        categoria:'moto',
        disponible:'si',
        year:'2019',
        imagen:'img/',
        marcaimagen:'img/marcas/keller.png'
    },
    {
        id:'007' ,
        linea:'150',
        modelo:'Hunter R/T 150',
        marca:'Corven',
        descripcion:'LLEVALA HOY MISMO + CASCO DE REGALO ',
        metodopago:'',
        categoria:'moto',
        disponible:'si',
        year:'2019',
        imagen:'img/',
        marcaimagen:'img/marcas/corven.png'
    },
    {
        id:'008',
        linea:'150',
        modelo:'Boxer R/T 150',
        marca:'Corven',
        descripcion:'LLEVALA HOY MISMO + CASCO DE REGALO ',
        metodopago:'',
        categoria:'moto',
        disponible:'si',
        year:'2019',
        imagen:'img/',
        marcaimagen:'img/marcas/corven.png'
    },
    {
        id:'009',
        linea:'135',
        modelo:'Rouser 135',
        marca:'Bajaj',
        descripcion:'LLEVALA HOY MISMO + CASCO DE REGALO ',
        metodopago:'',
        categoria:'moto',
        disponible:'si',
        year:'2019',
        imagen:'img/',
        marcaimagen:'img/marcas/bajaj.png'
    },
    {
        id:'010',
        linea:'125',
        modelo:'Skua 125',
        marca:'Motomel',
        descripcion:'LLEVALA HOY MISMO + CASCO DE REGALO ',
        metodopago:'',
        categoria:'moto',
        disponible:'si',
        year:'2019',
        imagen:'img/',
        marcaimagen:'img/marcas/motomel.png'
    },
    {
        id:'011',
        linea:'110',
        modelo:'Blitz Full 110',
        marca:'Motomel',
        descripcion:'LLEVALA HOY MISMO + CASCO DE REGALO ',
        metodopago:'',
        categoria:'moto',
        disponible:'si',
        year:'2019',
        imagen:'img/',
        marcaimagen:'img/marcas/motomel.png'
    },
    {
        id:'012',
        linea:'110',
        modelo:'Blitz Base 110',
        marca:'Motomel',
        descripcion:'LLEVALA HOY MISMO + CASCO DE REGALO ',
        metodopago:'',
        categoria:'moto',
        disponible:'si',
        year:'2019',
        imagen:'img/',
        marcaimagen:'img/marcas/motomel.png'
    },
    {
        id:'013',
        linea:'110',
        modelo:'LD 110 Max',
        marca:'Mondial',
        descripcion:'LLEVALA HOY MISMO + CASCO DE REGALO ',
        metodopago:'',
        categoria:'moto',
        disponible:'si',
        year:'2019',
        imagen:'img/',
        marcaimagen:'img/marcas/mondial.png'
    },
    {
        id:'014',
        linea:'110',
        modelo:'Crono Full 110',
        marca:'Keller',
        descripcion:'LLEVALA HOY MISMO + CASCO DE REGALO ',
        metodopago:'',
        categoria:'moto',
        disponible:'si',
        year:'2019',
        imagen:'img/',
        marcaimagen:'img/marcas/keller.png'
    },
    {
        id:'015',
        linea:'110',
        modelo:'Crono Classic 110',
        marca:'Keller',
        descripcion:'LLEVALA HOY MISMO + CASCO DE REGALO ',
        metodopago:'',
        categoria:'moto',
        disponible:'si',
        year:'2019',
        imagen:'img/',
        marcaimagen:'img/marcas/keller.png'
    },
    {
        id:'016',
        linea:'110',
        modelo:'Energy R/T R-2',
        marca:'Corven',
        descripcion:'LLEVALA HOY MISMO + CASCO DE REGALO ',
        metodopago:'',
        categoria:'moto',
        disponible:'si',
        year:'2019',
        imagen:'img/',
        marcaimagen:'img/marcas/corven.png'
    },
    {
        id:'017',
        linea:'110',
        modelo:'Energy A/D R-2',
        marca:'Corven',
        descripcion:'LLEVALA HOY MISMO + CASCO DE REGALO ',
        metodopago:'',
        categoria:'moto',
        disponible:'si',
        year:'2019',
        imagen:'img/',
        marcaimagen:'img/marcas/corven.png'
    }
];