// Ultimo ID es 23
const motos = [
   
    {
        id:'moto017',
        linea:'110',
        modelo:'Energy A/D R-2',
        marca:'Corven',
        descripcion:'LLEVALA HOY MISMO + CASCO DE REGALO ',
        metodopago:'',
        categoria:'moto',
        disponible:'si',
        year:'2019',
        imagen:'img/motos/Energy-110-R2/Energy-110-R2-old.png',
        foto1:'img/motos/Energy-110-R2/foto1.jpg',
        foto2:'img/motos/Energy-110-R2/foto2.jpg',
        foto3:'img/motos/Energy-110-R2/foto3.jpg',
        foto4:'img/motos/Energy-110-R2/foto4.jpg',
        foto5:'img/motos/Energy-110-R2/foto5.jpg',
        marcaimagen:'img/marcas/corven.png'
    },
    {
        id:'moto016',
        linea:'110',
        modelo:'Energy R/T R-2',
        marca:'Corven',
        descripcion:'LLEVALA HOY MISMO + CASCO DE REGALO ',
        metodopago:'',
        categoria:'moto',
        disponible:'si',
        year:'2019',
        imagen:'img/motos/Corven-Energy-RT/Corven-Energy-RT.png',
        foto1:'img/motos/Corven-Energy-RT/foto1.jpg',
        foto2:'img/motos/Corven-Energy-RT/foto2.jpg',
        foto3:'img/motos/Corven-Energy-RT/foto3.jpg',
        foto4:'img/motos/Corven-Energy-RT/foto4.jpg',
        foto5:'img/motos/Corven-Energy-RT/foto5.jpg',
        marcaimagen:'img/marcas/corven.png'
    },
    {
        id:'moto020',
        linea:'110',
        modelo:'DLX 110',
        marca:'Motomel',
        descripcion:'LLEVALA HOY MISMO + CASCO DE REGALO ',
        metodopago:'',
        categoria:'moto',
        disponible:'si',
        year:'2021',
        imagen:'img/motos/Motomel-Dlx-110/Motomel-Dlx-110.png',
        foto1:'img/motos/Motomel-Dlx-110/foto1.jpg',
        foto2:'img/motos/Motomel-Dlx-110/foto2.jpg',
        foto3:'img/motos/Motomel-Dlx-110/foto3.jpg',
        foto4:'img/motos/Motomel-Dlx-110/foto4.jpg',
        foto5:'img/motos/Motomel-Dlx-110/foto5.jpg',              
        marcaimagen:'img/marcas/motomel.png'
    },
    {
        id:'moto022',
        linea:'110',
        modelo:'B 110 AUTOMATICA',
        marca:'Motomel',
        descripcion:'LLEVALA HOY MISMO + CASCO DE REGALO ',
        metodopago:'',
        categoria:'moto',
        disponible:'si',
        year:'2020',
        imagen:'img/motos/Motomel-B-Automatica-110/Motomel-B-Automatica-110.png',
        foto1:'img/motos/Motomel-B-Automatica-110/foto1.jpg',
        foto2:'img/motos/Motomel-B-Automatica-110/foto2.jpg',
        foto3:'img/motos/Motomel-B-Automatica-110/foto3.jpg',
        foto4:'img/motos/Motomel-B-Automatica-110/foto4.jpg',
        foto5:'img/motos/Motomel-B-Automatica-110/foto5.jpg',              
        marcaimagen:'img/marcas/motomel.png'
    },
    {
        id:'moto023',
        linea:'110',
        modelo:'S110 MAX',
        marca:'Motomel',
        descripcion:'LLEVALA HOY MISMO + CASCO DE REGALO ',
        metodopago:'',
        categoria:'moto',
        disponible:'si',
        year:'2020',
        imagen:'img/motos/Motomel-S110-MAX/Motomel-S110-MAX.png',
        foto1:'img/motos/Motomel-S110-MAX/foto1.jpg',
        foto2:'img/motos/Motomel-S110-MAX/foto2.jpg',
        foto3:'img/motos/Motomel-S110-MAX/foto3.jpg',
        foto4:'img/motos/Motomel-S110-MAX/foto4.jpg',
        foto5:'img/motos/Motomel-S110-MAX/foto5.jpg',              
        marcaimagen:'img/marcas/motomel.png'
    },
   
    {
        id:'moto013',
        linea:'110',
        modelo:'LD 110 Max Base',
        marca:'Mondial',
        descripcion:'LLEVALA HOY MISMO + CASCO DE REGALO ',
        metodopago:'',
        categoria:'moto',
        disponible:'si',
        year:'2019',
        imagen:'img/motos/Mondial-LD-110-MAX-BASE/Mondial-LD-110-MAX-BASE.png',
        foto1:'img/motos/Mondial-LD-110-MAX-BASE/foto1.jpg',
        foto2:'img/motos/Mondial-LD-110-MAX-BASE/foto2.jpg',
        foto3:'img/motos/Mondial-LD-110-MAX-BASE/foto3.jpg',
        foto4:'img/motos/Mondial-LD-110-MAX-BASE/foto4.jpg',
        foto5:'img/motos/Mondial-LD-110-MAX-BASE/foto5.jpg',              
        marcaimagen:'img/marcas/mondial.png'
    },
    {
        id:'moto021',
        linea:'110',
        modelo:'LD Stroke 110',
        marca:'Mondial',
        descripcion:'LLEVALA HOY MISMO + CASCO DE REGALO ',
        metodopago:'',
        categoria:'moto',
        disponible:'si',
        year:'2019',
        imagen:'img/motos/Mondial-LD-Stroke-110/Mondial-LD-Stroke-110.png',
        foto1:'img/motos/Mondial-LD-Stroke-110/foto1.jpg',
        foto2:'img/motos/Mondial-LD-Stroke-110/foto2.jpg',
        foto3:'img/motos/Mondial-LD-Stroke-110/foto3.jpg',
        foto4:'img/motos/Mondial-LD-Stroke-110/foto4.jpg',
        foto5:'img/motos/Mondial-LD-Stroke-110/foto5.jpg',              
        marcaimagen:'img/marcas/mondial.png'
    },
    {
        id:'moto018',
        linea:'110',
        modelo:'LD 110 Max Full',
        marca:'Mondial',
        descripcion:'LLEVALA HOY MISMO + CASCO DE REGALO ',
        metodopago:'',
        categoria:'moto',
        disponible:'si',
        year:'2019',
        imagen:'img/motos/Mondial-LD-110-MAX-FULL/Mondial-LD-110-MAX-FULL.png',
        foto1:'img/motos/Mondial-LD-110-MAX-FULL/foto1.jpg',
        foto2:'img/motos/Mondial-LD-110-MAX-FULL/foto2.jpg',
        foto3:'img/motos/Mondial-LD-110-MAX-FULL/foto3.jpg',
        foto4:'img/motos/Mondial-LD-110-MAX-FULL/foto4.jpg',
        foto5:'img/motos/Mondial-LD-110-MAX-FULL/foto5.jpg',              
        marcaimagen:'img/marcas/mondial.png'
    },
    {
        id:'moto012',
        linea:'110',
        modelo:'Blitz Base 110',
        marca:'Motomel',
        descripcion:'LLEVALA HOY MISMO + CASCO DE REGALO ',
        metodopago:'',
        categoria:'moto',
        disponible:'si',
        year:'2019',
        imagen:'img/motos/Motomel-Blitz-Base-110/Motomel-Blitz-Base-110.png',
        foto1:'img/motos/Motomel-Blitz-Base-110/foto1.jpg',
        foto2:'img/motos/Motomel-Blitz-Base-110/foto2.jpg',
        foto3:'img/motos/Motomel-Blitz-Base-110/foto3.jpg',
        foto4:'img/motos/Motomel-Blitz-Base-110/foto4.jpg',
        foto5:'img/motos/Motomel-Blitz-Base-110/foto5.jpg',     
        marcaimagen:'img/marcas/motomel.png'
    },
    {
        id:'moto011',
        linea:'110',
        modelo:'Blitz Full 110',
        marca:'Motomel',
        descripcion:'LLEVALA HOY MISMO + CASCO DE REGALO ',
        metodopago:'',
        categoria:'moto',
        disponible:'si',
        year:'2019',
        imagen:'img/motos/Motomel-Blitz-Full-110/Motomel-Blitz-Full-110.png',
        foto1:'img/motos/Motomel-Blitz-Full-110/foto1.jpg',
        foto2:'img/motos/Motomel-Blitz-Full-110/foto2.jpg',
        foto3:'img/motos/Motomel-Blitz-Full-110/foto3.jpg',
        foto4:'img/motos/Motomel-Blitz-Full-110/foto4.jpg',
        foto5:'img/motos/Motomel-Blitz-Full-110/foto5.jpg',  
        marcaimagen:'img/marcas/motomel.png'
    },
    {
        id:'moto015',
        linea:'110',
        modelo:'Crono Classic 110',
        marca:'Keller',
        descripcion:'LLEVALA HOY MISMO + CASCO DE REGALO ',
        metodopago:'',
        categoria:'moto',
        disponible:'si',
        year:'2019',
        imagen:'img/motos/Keller-Crono-Classic-110/Keller-Crono-Classic-110.png',
        foto1:'img/motos/Keller-Crono-Classic-110/foto1.jpg',
        foto2:'img/motos/Keller-Crono-Classic-110/foto2.jpg',
        foto3:'img/motos/Keller-Crono-Classic-110/foto3.jpg',
        foto4:'img/motos/Keller-Crono-Classic-110/foto4.jpg',
        foto5:'img/motos/Keller-Crono-Classic-110/foto5.jpg',       
        marcaimagen:'img/marcas/keller.png'
    },
    {
        id:'moto014',
        linea:'110',
        modelo:'Crono Full 110',
        marca:'Keller',
        descripcion:'LLEVALA HOY MISMO + CASCO DE REGALO ',
        metodopago:'',
        categoria:'moto',
        disponible:'si',
        year:'2019',
        imagen:'img/motos/Keller-Crono-Full-110/Keller-Crono-Full-110.png',
        foto1:'img/motos/Keller-Crono-Full-110/foto1.jpg',
        foto2:'img/motos/Keller-Crono-Full-110/foto2.jpg',
        foto3:'img/motos/Keller-Crono-Full-110/foto3.jpg',
        foto4:'img/motos/Keller-Crono-Full-110/foto4.jpg',
        foto5:'img/motos/Keller-Crono-Full-110/foto5.jpg',          
        marcaimagen:'img/marcas/keller.png'
    },
    {
        id:'moto010',
        linea:'125',
        modelo:'Skua 125',
        marca:'Motomel',
        descripcion:'LLEVALA HOY MISMO + CASCO DE REGALO ',
        metodopago:'',
        categoria:'moto',
        disponible:'si',
        year:'2019',
        imagen:'img/motos/Motomel-Skua-125/Motomel-Skua-125.png',
        foto1:'img/motos/Motomel-Skua-125/foto1.jpg',
        foto2:'img/motos/Motomel-Skua-125/foto2.jpg',
        foto3:'img/motos/Motomel-Skua-125/foto3.jpg',
        foto4:'img/motos/Motomel-Skua-125/foto4.jpg',
        foto5:'img/motos/Motomel-Skua-125/foto5.jpg',  
        marcaimagen:'img/marcas/motomel.png'
    },
    {
        id:'moto009',
        linea:'135',
        modelo:'Rouser 135',
        marca:'Bajaj',
        descripcion:'LLEVALA HOY MISMO + CASCO DE REGALO ',
        metodopago:'',
        categoria:'moto',
        disponible:'si',
        year:'2019',
        imagen:'img/motos/Bajaj-Rouser-135/Bajaj-Rouser-135.png',
        foto1:'img/motos/Bajaj-Rouser-135/foto1.jpg',
        foto2:'img/motos/Bajaj-Rouser-135/foto2.jpg',
        foto3:'img/motos/Bajaj-Rouser-135/foto3.jpg',
        foto4:'img/motos/Bajaj-Rouser-135/foto4.jpg',
        foto5:'img/motos/Bajaj-Rouser-135/foto5.jpg',  
        marcaimagen:'img/marcas/bajaj.png'
    },
    {
        id:'moto008',
        linea:'150',
        modelo:'Boxer R/T 150',
        marca:'Corven',
        descripcion:'LLEVALA HOY MISMO + CASCO DE REGALO ',
        metodopago:'',
        categoria:'moto',
        disponible:'si',
        year:'2019',
        imagen:'img/motos/Corven-Boxer-RT-150/Corven-Boxer-RT-150.png',
        foto1:'img/motos/Corven-Boxer-RT-150/foto1.jpg',
        foto2:'img/motos/Corven-Boxer-RT-150/foto2.jpg',
        foto3:'img/motos/Corven-Boxer-RT-150/foto3.jpg',
        foto4:'img/motos/Corven-Boxer-RT-150/foto4.jpg',
        foto5:'img/motos/Corven-Boxer-RT-150/foto5.jpg', 
        marcaimagen:'img/marcas/corven.png'
    },
    {
        id:'moto007' ,
        linea:'150',
        modelo:'Hunter R/T 150',
        marca:'Corven',
        descripcion:'LLEVALA HOY MISMO + CASCO DE REGALO ',
        metodopago:'',
        categoria:'moto',
        disponible:'si',
        year:'2019',
        imagen:'img/motos/Corven-Hunter-RT/Corven-Hunter-RT-150.png',
        foto1:'img/motos/Corven-Hunter-RT/foto1.jpg',
        foto2:'img/motos/Corven-Hunter-RT/foto2.jpg',
        foto3:'img/motos/Corven-Hunter-RT/foto3.jpg',
        foto4:'img/motos/Corven-Hunter-RT/foto4.jpg',
        foto5:'img/motos/Corven-Hunter-RT/foto5.jpg', 
        marcaimagen:'img/marcas/corven.png'
    },
    {
        id:'moto006',
        linea:'150',
        modelo:'Miracle Cross',
        marca:'Keller',
        descripcion:'LLEVALA HOY MISMO + CASCO DE REGALO ',
        metodopago:'',
        categoria:'moto',
        disponible:'si',
        year:'2019',
        imagen:'img/motos/Keller-Miracle-150/Keller-Miracle-150.png',
        foto1:'img/motos/Keller-Miracle-150/foto1.jpg',
        foto2:'img/motos/Keller-Miracle-150/foto2.jpg',
        foto3:'img/motos/Keller-Miracle-150/foto3.jpg',
        foto4:'img/motos/Keller-Miracle-150/foto4.jpg',
        foto5:'img/motos/Keller-Miracle-150/foto5.jpg', 
        marcaimagen:'img/marcas/keller.png'
    },      
    {
        id:'moto005',
        linea:'150',
        modelo:'Stratus Base 150',
        marca:'Keller',
        descripcion:'LLEVALA HOY MISMO + CASCO DE REGALO ',
        metodopago:'',
        categoria:'moto',
        disponible:'si',
        year:'2019',
        imagen:'img/motos/Keller-Stratus-Base-150/Keller-Stratus-Base-150.png',
        foto1:'img/motos/Keller-Stratus-Base-150/foto1.jpg',
        foto2:'img/motos/Keller-Stratus-Base-150/foto2.jpg',
        foto3:'img/motos/Keller-Stratus-Base-150/foto3.jpg',
        foto4:'img/motos/Keller-Stratus-Base-150/foto4.jpg',
        foto5:'img/motos/Keller-Stratus-Base-150/foto5.jpg', 
        marcaimagen:'img/marcas/keller.png'
    },
    {
        id:'moto004',
        linea:'150',
        modelo:'CG 150 S2 Tubular',
        marca:'Motomel',
        descripcion:'LLEVALA HOY MISMO + CASCO DE REGALO ',
        metodopago:'',
        categoria:'moto',
        disponible:'si',
        year:'2019',
        imagen:'img/motos/Motomel-CG-S2-150/Motomel-CG-S2-150.png',
        foto1:'img/motos/Motomel-CG-S2-150/foto1.jpg',
        foto2:'img/motos/Motomel-CG-S2-150/foto2.jpg',
        foto3:'img/motos/Motomel-CG-S2-150/foto3.jpg',
        foto4:'img/motos/Motomel-CG-S2-150/foto4.jpg',
        foto5:'img/motos/Motomel-CG-S2-150/foto5.jpg', 
        marcaimagen:'img/marcas/motomel.png'
    },
    {
        id:'moto002',
        linea:'150',
        modelo:'CG 150 S3',
        marca:'Motomel',
        descripcion:'LLEVALA HOY MISMO + CASCO DE REGALO ',
        metodopago:'',
        categoria:'moto',
        disponible:'si',
        year:'2020',
        imagen:'img/motos/Motomel-CG-S3-150/Motomel-CG-S3-150.png',
        foto1:'img/motos/Motomel-CG-S3-150/foto1.jpg',
        foto2:'img/motos/Motomel-CG-S3-150/foto2.jpg',
        foto3:'img/motos/Motomel-CG-S3-150/foto3.jpg',
        foto4:'img/motos/Motomel-CG-S3-150/foto4.jpg',
        foto5:'img/motos/Motomel-CG-S3-150/foto5.jpg', 
        marcaimagen:'img/marcas/motomel.png'
    },
    {
        id:'moto003',
        linea:'150',
        modelo:'Skua 150 New Cross',
        marca:'Motomel',
        descripcion:'LLEVALA HOY MISMO + CASCO DE REGALO ',
        metodopago:'',
        categoria:'moto',
        disponible:'si',
        year:'2019',
        imagen:'img/motos/Motomel-Skua-150/Motomel-SKUA-150.png',
        foto1:'img/motos/Motomel-Skua-150/foto1.jpg',
        foto2:'img/motos/Motomel-Skua-150/foto2.jpg',
        foto3:'img/motos/Motomel-Skua-150/foto3.jpg',
        foto4:'img/motos/Motomel-Skua-150/foto4.jpg',
        foto5:'img/motos/Motomel-Skua-150/foto5.jpg', 
        marcaimagen:'img/marcas/motomel.png'
    },
    // {
    //     id:'moto002',
    //     linea:'150',
    //     modelo:'RX 150 Z7',
    //     marca:'Zanella',
    //     descripcion:'LLEVALA HOY MISMO + CASCO DE REGALO ',
    //     metodopago:'',
    //     categoria:'moto',
    //     disponible:'si',
    //     year:'2019',
    //     imagen:'img/motos/Zanella-RX-150-Z7.jpg',
    //     marcaimagen:'img/marcas/zanella.jpg'
    // },
    
    {
        id:'moto001',
        linea:'200',
        modelo:'Rouser NS 200',
        marca:'Bajaj',
        descripcion:'LLEVALA HOY MISMO + CASCO DE REGALO ',
        metodopago:'',
        categoria:'moto',
        disponible:'si',
        year:'2019',
        imagen:'img/motos/Rouser200/ROUSER200.png',
        foto1:'img/motos/Rouser200/foto1.jpg',
        foto2:'img/motos/Rouser200/foto2.jpg',
        foto3:'img/motos/Rouser200/foto3.jpg',
        foto4:'img/motos/Rouser200/foto4.jpg',
        foto5:'img/motos/Rouser200/foto5.jpg', 
        marcaimagen:'img/marcas/bajaj.png'
    }
   
    
];